// Generated by CoffeeScript 1.3.3
(function() {

  this.ResponsiveImage = (function() {

    function ResponsiveImage(element) {
      this.element = element;
    }

    ResponsiveImage.prototype.element = ResponsiveImage.element;

    ResponsiveImage.prototype.mobile = function() {
      return true;
    };

    return ResponsiveImage;

  })();

}).call(this);
