// Generated by CoffeeScript 1.3.3
(function() {
  var $;

  $ = jQuery;

  this.ResponsiveImage = (function() {

    function ResponsiveImage(name) {
      this.name = name;
    }

    ResponsiveImage.prototype.doSomething = function() {
      return console.log("something");
    };

    return ResponsiveImage;

  })();

  $.fn.makeResponsive = function() {
    var ri;
    ri = new ResponsiveImage();
    return ri.doSomething();
  };

}).call(this);
