// Generated by CoffeeScript 1.3.3
(function() {

  this.ResponsiveImage = (function() {

    function ResponsiveImage() {}

    ResponsiveImage.prototype.mobile = function() {
      return true;
    };

    return ResponsiveImage;

  })();

}).call(this);
