// Generated by CoffeeScript 1.3.3
(function() {
  var replaceResponsiveImage;

  replaceResponsiveImage = function(img) {
    var highestMatch, mediaSource;
    if (img.data("original-src") == null) {
      img.data("original-src", img.prop("src"));
    }
    highestMatch = 0;
    mediaSource = void 0;
    img.nextAll("source").each(function() {
      var mediaQuery, screenWidth;
      mediaQuery = $(this).prop("media");
      if (matchMedia(mediaQuery).matches) {
        screenWidth = mediaQuery.match(/\d+/);
        if (screenWidth >= highestMatch) {
          highestMatch = screenWidth;
          return mediaSource = $(this).prop("src");
        }
      }
    });
    if (highestMatch > 0) {
      return img.prop("src", mediaSource);
    } else {
      return img.prop("src", img.data("original-src"));
    }
  };

  jQuery(document).ready(function() {
    $("img").each(function() {
      return replaceResponsiveImage($(this));
    });
    return $(window).resize(function(event) {
      return $("img").each(function() {
        return replaceResponsiveImage($(this));
      });
    });
  });

}).call(this);
