// Generated by CoffeeScript 1.3.3
(function() {
  var el, responsivePicture;

  el = '<picture>\
        <source media="(min-width: 980px)" srcset="images/large-1.jpg 1x">\
        <source media="(min-width: 768px)" srcset="images/med-1.jpg 1x">\
        <source srcset="images/small-1.jpg 1x">\
        <img src="images/small-1.jpg" alt="">\
      </picture>';

  responsivePicture = new ResponsivePicture($(el));

  describe("jQuery extendo", function() {
    return it("responds to responsivePicture", function() {
      return expect($(el).responsivePicture()).toBeDefined;
    });
  });

  describe("ResponsiveImage", function() {
    return describe("media query logic", function() {
      return it("grabs the width from the media attr", function() {
        return expect(responsivePicture._getMediaQueryMinWidth("<source media='(min-width: 1200px)'>")).toBe(1200);
      });
    });
  });

}).call(this);
