// Generated by CoffeeScript 1.3.3
(function() {
  var el, responsiveImage;

  el = '<picture>\
        <source media="(min-width: 980px)" srcset="images/large-1.jpg 1x">\
        <source media="(min-width: 768px)" srcset="images/med-1.jpg 1x">\
        <source srcset="images/small-1.jpg 1x"> \
        <img src="images/small-1.jpg" alt=""> \
      </picture>';

  responsiveImage = new ResponsiveImage($(el));

  describe("jQuery extendo", function() {
    return it("responds to makeResponsive", function() {
      return expect($(el).makeResponsive()).toBeDefined;
    });
  });

  describe("ResponsiveImage", function() {
    return describe("media query logic", function() {
      return it("grabs the width from the media attr", function() {
        return expect(responsiveImage._getMediaQueryMinWidth("<source media='(min-width: 1200px)'>")).toBe(1200);
      });
    });
  });

}).call(this);
