// Generated by CoffeeScript 1.3.3
(function() {

  describe("ResponsiveImage", function() {
    return it("responds to mobile", function() {
      var image;
      image = new ResponsiveImage($('img'));
      return expect(image.element).toEqual($('img'));
    });
  });

}).call(this);
